# Site settings
title: Stef치n J칩hannsson
baseurl: "/cv"
url: "https://sevensteves-com.github.io/cv/"
google_analytics: # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: Stef치n J칩hannsson
  desc: DevOps Engineer, Infrastructure Engineer, Site Reliability Engineer
  email: stefaj9@gmail.com

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  facebook: 
  flickr:
  github: sevensteves
  google_plus:
  instagram:
  keybase:
  linkedin: https://www.linkedin.com/in/stefan-johannsson/ 
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter: 
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"