title: "Stefán Jóhnnsson"
email: stefaj9@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This CV showcases my experience in DevOps, cloud services, and automation, 
  focused on optimizing system performance and reliability.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  sevensteves
linkedin_username: stefan-johannsson

# Build settings
theme: minima
plugins:
  - jekyll-feed
